// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/tomblanc/stromboli",
        "contact": {
            "name": "API Support",
            "url": "https://stromboli/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/claude/status": {
            "get": {
                "description": "Checks if Claude credentials are configured",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Claude status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ClaudeStatusResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/run": {
            "post": {
                "description": "Executes Claude Code in an isolated Podman container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execution"
                ],
                "summary": "Run Claude",
                "parameters": [
                    {
                        "description": "Run request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.RunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RunResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RunResponse"
                        }
                    },
                    "500": {
                        "description": "Execution failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RunResponse"
                        }
                    },
                    "503": {
                        "description": "Claude not configured",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RunResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.ClaudeOptions": {
            "description": "All available Claude CLI options for headless execution",
            "type": "object",
            "properties": {
                "add_dirs": {
                    "description": "Additional directories for tool access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "agent": {
                    "description": "Agent for current session",
                    "type": "string",
                    "example": "reviewer"
                },
                "agents": {
                    "description": "Custom agents definition (JSON object)",
                    "type": "object",
                    "additionalProperties": {}
                },
                "allow_dangerously_skip_permissions": {
                    "description": "Enable bypass as an option without enabling by default",
                    "type": "boolean",
                    "example": false
                },
                "allowed_tools": {
                    "description": "Allowed tools with patterns (e.g., \"Bash(git:*)\")",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Bash(git:*)",
                        "Read"
                    ]
                },
                "append_system_prompt": {
                    "description": "Append to default system prompt",
                    "type": "string",
                    "example": "Focus on security best practices"
                },
                "betas": {
                    "description": "Beta headers for API requests",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "continue": {
                    "description": "Continue most recent conversation in workspace",
                    "type": "boolean",
                    "example": false
                },
                "dangerously_skip_permissions": {
                    "description": "Bypass all permission checks (use in sandboxed environments only)",
                    "type": "boolean",
                    "example": true
                },
                "debug": {
                    "description": "Debug mode with optional category filter",
                    "type": "string",
                    "example": "api,hooks"
                },
                "disable_slash_commands": {
                    "description": "Disable all slash commands/skills",
                    "type": "boolean",
                    "example": false
                },
                "disallowed_tools": {
                    "description": "Denied tools",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Write"
                    ]
                },
                "fallback_model": {
                    "description": "Fallback model when default is overloaded",
                    "type": "string",
                    "example": "haiku"
                },
                "files": {
                    "description": "File resources (format: file_id:path)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fork_session": {
                    "description": "Create new session ID when resuming",
                    "type": "boolean",
                    "example": false
                },
                "include_partial_messages": {
                    "description": "Include partial message chunks (stream-json only)",
                    "type": "boolean",
                    "example": false
                },
                "input_format": {
                    "description": "Input format: text, stream-json",
                    "type": "string",
                    "example": "text"
                },
                "json_schema": {
                    "description": "JSON Schema for structured output validation",
                    "type": "string",
                    "example": "{\"type\":\"object\"}"
                },
                "max_budget_usd": {
                    "description": "Maximum dollar amount for API calls",
                    "type": "number",
                    "example": 5
                },
                "mcp_configs": {
                    "description": "MCP server config files or JSON strings",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "model": {
                    "description": "Model alias (sonnet, opus, haiku) or full name",
                    "type": "string",
                    "example": "sonnet"
                },
                "no_persistence": {
                    "description": "Don't save session to disk",
                    "type": "boolean",
                    "example": false
                },
                "output_format": {
                    "description": "Output format: text, json, stream-json",
                    "type": "string",
                    "example": "json"
                },
                "permission_mode": {
                    "description": "Permission mode: acceptEdits, bypassPermissions, default, delegate, dontAsk, plan",
                    "type": "string",
                    "example": "bypassPermissions"
                },
                "plugin_dirs": {
                    "description": "Plugin directories",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "replay_user_messages": {
                    "description": "Re-emit user messages on stdout",
                    "type": "boolean",
                    "example": false
                },
                "session_id": {
                    "description": "Resume by session ID (UUID)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "setting_sources": {
                    "description": "Setting sources to load: user, project, local",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "user",
                        "project"
                    ]
                },
                "settings": {
                    "description": "Path to settings JSON file or JSON string",
                    "type": "string"
                },
                "strict_mcp_config": {
                    "description": "Only use MCP servers from mcp_configs",
                    "type": "boolean",
                    "example": false
                },
                "system_prompt": {
                    "description": "Replace default system prompt",
                    "type": "string",
                    "example": "You are a senior Go developer"
                },
                "tools": {
                    "description": "Built-in tools (\"\", \"default\", or specific names)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Bash",
                        "Read",
                        "Edit"
                    ]
                },
                "verbose": {
                    "description": "Enable verbose mode",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_api.ClaudeStatusResponse": {
            "description": "Claude configuration status",
            "type": "object",
            "properties": {
                "configured": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "Claude is configured"
                }
            }
        },
        "internal_api.HealthResponse": {
            "description": "Health check response",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "stromboli"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_api.PodmanOptions": {
            "description": "Podman container mount configuration",
            "type": "object",
            "properties": {
                "volumes": {
                    "description": "Volume mounts (host:container or host:container:options format)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "/data:/data:ro"
                    ]
                }
            }
        },
        "internal_api.RunRequest": {
            "description": "Request to execute Claude Code in an isolated container",
            "type": "object",
            "required": [
                "prompt"
            ],
            "properties": {
                "claude": {
                    "description": "Claude configuration - all CLI options exposed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_api.ClaudeOptions"
                        }
                    ]
                },
                "podman": {
                    "description": "Podman configuration",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_api.PodmanOptions"
                        }
                    ]
                },
                "prompt": {
                    "description": "Required: the prompt to send to Claude",
                    "type": "string",
                    "example": "Analyze this code and suggest improvements"
                },
                "workspace": {
                    "description": "Workspace to mount (host path -\u003e /workspace in container)",
                    "type": "string",
                    "example": "/home/user/project"
                }
            }
        },
        "internal_api.RunResponse": {
            "description": "Response from Claude execution",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message (when failed)",
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "description": "Unique run identifier",
                    "type": "string",
                    "example": "run-abc123def456"
                },
                "output": {
                    "description": "Claude's output (when successful)",
                    "type": "string",
                    "example": "Here is my analysis..."
                },
                "session_id": {
                    "description": "Session ID for conversation continuation",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "description": "Execution status: completed, error",
                    "type": "string",
                    "example": "completed"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "OAuth2 Bearer token (future)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Stromboli API",
	Description:      "Claude Code container orchestration API - secure, isolated AI execution",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
