Third-Party Licenses for Stromboli
====================================

This file lists the licenses of all third-party dependencies used by Stromboli.

Generated by go-licenses (https://github.com/google/go-licenses)

{{ range . }}
================================================================================
Module:  {{ .Name }}
License: {{ .LicenseName }}
URL:     {{ .LicenseURL }}
================================================================================

{{ .LicenseText }}

{{ end }}
